{{- if not .Values.existingSecret -}}
{{- if not .Values.token -}}
{{- fail "Either .Values.token or .Values.existingSecret must be set" -}}
{{- end -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "logsmith-connector.fullname" . }}
  labels:
    {{- include "logsmith-connector.labels" . | nindent 4 }}
type: Opaque
stringData:
  token: {{ .Values.token | quote }}
{{- end -}}
